數據分析，能不用迴圈做計算就不要用迴圈，
原因為計算速度上的問題。

In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [3]:
p = [1096.96, 596.95, 896.95]

In [4]:
c= 30.1

In [5]:
prices = np.array(p)

In [6]:
prices

array([ 1096.96,   596.95,   896.95])

In [7]:
print(prices)

[ 1096.96   596.95   896.95]


In [8]:
prices*c

array([ 33018.496,  17968.195,  26998.195])

### 不到最後關頭絕不輕言使用list。較好的選擇是array。

In [9]:
p*c

TypeError: can't multiply sequence by non-int of type 'float'

list 沒辦法直接做計算，需要轉成矩正。